/**
 * Icon components using react-icons (Lucide set).
 * Re-exported with consistent naming for the app.
 */

import {
  LuTrash2,
  LuArrowUp,
  LuChevronLeft,
  LuCheck,
  LuCirclePlus,
  LuCircleStop,
  LuX,
  LuSettings,
  LuSearch,
  LuMessageCircle,
  LuFileText,
  LuClock,
  LuChevronDown,
  LuChevronUp,
  LuChevronRight,
  LuGitBranch,
  LuDownload,
  LuPlay,
  LuPencil,
  LuGripHorizontal,
  LuRefreshCw,
  LuInfo,
  LuBomb,
  LuUsers,
  LuCopy,
  LuLayers,
  LuPlus,
  LuTriangleAlert,
  LuCode,
  LuLayoutList,
  LuMessageSquareText,
  LuThumbsUp,
  LuThumbsDown,
  LuSquarePen,
  LuStar,
  LuArchive,
  LuShare2,
  LuEllipsisVertical,
  LuHouse,
  LuSparkles,
  LuExternalLink,
  LuEye,
  LuPackage,
  LuBrain,
  LuLogOut,
  LuHistory,
  LuSend,
  LuLoader,
  LuImage,
  LuChartBar,
  LuUserRound,
  LuZap,
  LuBot,
  LuWorkflow,
  LuWrench,
} from "react-icons/lu";

// Re-export with app-specific names
export {
  LuTrash2 as TrashIcon,
  LuArrowUp as ArrowUpIcon,
  LuChevronLeft as ChevronLeftIcon,
  LuCheck as CheckIcon,
  LuCirclePlus as PlusCircleIcon,
  LuCircleStop as StopCircleIcon,
  LuX as CloseIcon,
  LuSettings as GearIcon,
  LuSearch as SearchIcon,
  LuMessageCircle as ChatIcon,
  LuFileText as DocumentIcon,
  LuClock as ClockIcon,
  LuChevronDown as ChevronDownIcon,
  LuChevronUp as ChevronUpIcon,
  LuChevronRight as ChevronRightIcon,
  LuGitBranch as ForkIcon,
  LuDownload as SaveIcon,
  LuPlay as PlayIcon,
  LuPencil as EditIcon,
  LuPencil as PencilIcon,
  LuChevronUp as ArrowUpSmallIcon,
  LuChevronDown as ArrowDownSmallIcon,
  LuGripHorizontal as ReorderIcon,
  LuRefreshCw as RefreshIcon,
  LuInfo as InfoIcon,
  LuUsers as UsersIcon,
  LuCopy as CopyIcon,
  LuLayers as CategoryIcon,
  LuPlus as PlusIcon,
  LuTriangleAlert as AlertIcon,
  LuCode as CodeIcon,
  LuLayoutList as LayoutIcon,
  LuMessageSquareText as FeedbackIcon,
  LuThumbsUp as ThumbsUpIcon,
  LuThumbsDown as ThumbsDownIcon,
  LuSquarePen as ComposeIcon,
  LuStar as StarIcon,
  LuArchive as ArchiveIcon,
  LuShare2 as ShareIcon,
  LuEllipsisVertical as MoreIcon,
  LuHouse as HouseIcon,
  LuSparkles as SparklesIcon,
  LuExternalLink as ExternalLinkIcon,
  LuEye as EyeIcon,
  LuPackage as PackageIcon,
  LuBrain as BrainIcon,
  LuLogOut as LogOutIcon,
  LuHistory as HistoryIcon,
  LuSend as SendIcon,
  LuLoader as LoaderIcon,
  LuImage as ImageIcon,
  LuChartBar as BarChartIcon,
  LuUserRound as UserIcon,
  LuZap as BoltIcon,
  LuBot as BotIcon,
  LuWorkflow as WorkflowIcon,
  LuWrench as WrenchIcon,
};
